title: My Website
description: A website with multiple pages and LaTeX support.

# 设置导航栏链接
navbar:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Contact
    url: /contact

# 其他Jekyll相关配置
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima
